name: Rust Test and Clippy on PR

on:
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always
  LIBTORCH_BASE_DIR: ${{ github.workspace }}/opt/torch
  LIBTORCH: ${{ github.workspace }}/opt/torch/libtorch
  RUSTUP_TOOLCHAIN: nightly
  TORCH_VERSION: 2.7.0

jobs:
  rust-check:
    runs-on: ubuntu-24.04
    name: Run Rust Tests and Clippy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-

      - name: Cache libtorch
        id: cache-libtorch
        uses: actions/cache@v4
        with:
          path: ${{ env.LIBTORCH }}
          key: ${{ runner.os }}-libtorch-${{ env.TORCH_VERSION }}
          restore-keys: |
            ${{ runner.os }}-libtorch-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev pkg-config

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Download and extract LibTorch (if cache miss)
        if: steps.cache-libtorch.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ env.LIBTORCH_BASE_DIR }}
          curl -sSL https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${{ env.TORCH_VERSION }}%2Bcpu.zip  --output libtorch.zip
          unzip -q libtorch.zip -d ${{ env.LIBTORCH_BASE_DIR }}
          rm libtorch.zip

      - name: Run cargo test
        run: cargo test --verbose
        env:
          LIBTORCH: ${{ env.LIBTORCH }}
          LD_LIBRARY_PATH: ${{ env.LIBTORCH }}/lib:$LD_LIBRARY_PATH

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings